import { Component, ViewEncapsulation } from '@angular/core';
import { MaterialIconsRegistry, } from '@triangular/material-icons';

import {
  materialIconIcImage24Px,
  materialIconIcImage48Px,
  materialIconIcImageAspectRatio24Px,
  materialIconIcImageAspectRatio48Px,
  materialIconIcImportContacts24Px,
  materialIconIcImportContacts48Px,
  materialIconIcImportExport24Px,
  materialIconIcImportExport48Px,
  materialIconIcImportantDevices24Px,
  materialIconIcImportantDevices48Px,
  materialIconIcInbox24Px,
  materialIconIcInbox48Px,
  materialIconIcIndeterminateCheckBox24Px,
  materialIconIcInfo24Px,
  materialIconIcInfo48Px,
  materialIconIcInfoOutline24Px,
  materialIconIcInfoOutline48Px,
  materialIconIcInput24Px,
  materialIconIcInput48Px,
  materialIconIcInsertChart18Px,
  materialIconIcInsertChart24Px,
  materialIconIcInsertChart48Px,
  materialIconIcInsertComment18Px,
  materialIconIcInsertComment24Px,
  materialIconIcInsertComment48Px,
  materialIconIcInsertDriveFile18Px,
  materialIconIcInsertDriveFile24Px,
  materialIconIcInsertDriveFile48Px,
  materialIconIcInsertEmoticon18Px,
  materialIconIcInsertEmoticon24Px,
  materialIconIcInsertEmoticon48Px,
  materialIconIcInsertInvitation18Px,
  materialIconIcInsertInvitation24Px,
  materialIconIcInsertInvitation48Px,
  materialIconIcInsertLink18Px,
  materialIconIcInsertLink24Px,
  materialIconIcInsertLink48Px,
  materialIconIcInsertPhoto18Px,
  materialIconIcInsertPhoto24Px,
  materialIconIcInsertPhoto48Px,
  materialIconIcInvertColors24Px,
  materialIconIcInvertColors48Px,
  materialIconIcInvertColorsOff24Px,
  materialIconIcInvertColorsOff48Px,
  materialIconIcIso24Px,
  materialIconIcIso48Px,
} from '@triangular/material-icons/icons';

@Component({
  selector: 'app-icons-i',
  templateUrl: './icons-i.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
})
export class IconsIComponent {
  icons = [
    materialIconIcImage24Px,
    materialIconIcImage48Px,
    materialIconIcImageAspectRatio24Px,
    materialIconIcImageAspectRatio48Px,
    materialIconIcImportContacts24Px,
    materialIconIcImportContacts48Px,
    materialIconIcImportExport24Px,
    materialIconIcImportExport48Px,
    materialIconIcImportantDevices24Px,
    materialIconIcImportantDevices48Px,
    materialIconIcInbox24Px,
    materialIconIcInbox48Px,
    materialIconIcIndeterminateCheckBox24Px,
    materialIconIcInfo24Px,
    materialIconIcInfo48Px,
    materialIconIcInfoOutline24Px,
    materialIconIcInfoOutline48Px,
    materialIconIcInput24Px,
    materialIconIcInput48Px,
    materialIconIcInsertChart18Px,
    materialIconIcInsertChart24Px,
    materialIconIcInsertChart48Px,
    materialIconIcInsertComment18Px,
    materialIconIcInsertComment24Px,
    materialIconIcInsertComment48Px,
    materialIconIcInsertDriveFile18Px,
    materialIconIcInsertDriveFile24Px,
    materialIconIcInsertDriveFile48Px,
    materialIconIcInsertEmoticon18Px,
    materialIconIcInsertEmoticon24Px,
    materialIconIcInsertEmoticon48Px,
    materialIconIcInsertInvitation18Px,
    materialIconIcInsertInvitation24Px,
    materialIconIcInsertInvitation48Px,
    materialIconIcInsertLink18Px,
    materialIconIcInsertLink24Px,
    materialIconIcInsertLink48Px,
    materialIconIcInsertPhoto18Px,
    materialIconIcInsertPhoto24Px,
    materialIconIcInsertPhoto48Px,
    materialIconIcInvertColors24Px,
    materialIconIcInvertColors48Px,
    materialIconIcInvertColorsOff24Px,
    materialIconIcInvertColorsOff48Px,
    materialIconIcIso24Px,
    materialIconIcIso48Px,
  ];

  constructor(private registry: MaterialIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
