import { Component, ViewEncapsulation } from '@angular/core';
import { MaterialIconsRegistry, } from '@triangular/material-icons';

import {
  materialIconIcHd24Px,
  materialIconIcHdrOff24Px,
  materialIconIcHdrOff48Px,
  materialIconIcHdrOn24Px,
  materialIconIcHdrOn48Px,
  materialIconIcHdrStrong24Px,
  materialIconIcHdrStrong48Px,
  materialIconIcHdrWeak24Px,
  materialIconIcHdrWeak48Px,
  materialIconIcHeadset24Px,
  materialIconIcHeadset48Px,
  materialIconIcHeadsetMic24Px,
  materialIconIcHeadsetMic48Px,
  materialIconIcHealing24Px,
  materialIconIcHealing48Px,
  materialIconIcHearing24Px,
  materialIconIcHearing48Px,
  materialIconIcHelp24Px,
  materialIconIcHelp48Px,
  materialIconIcHelpOutline24Px,
  materialIconIcHighQuality24Px,
  materialIconIcHighQuality48Px,
  materialIconIcHighlight24Px,
  materialIconIcHighlight48Px,
  materialIconIcHighlightOff24Px,
  materialIconIcHighlightOff48Px,
  materialIconIcHistory24Px,
  materialIconIcHistory48Px,
  materialIconIcHome24Px,
  materialIconIcHome48Px,
  materialIconIcHotTub24Px,
  materialIconIcHotTub48Px,
  materialIconIcHotel24Px,
  materialIconIcHotel48Px,
  materialIconIcHourglassEmpty24Px,
  materialIconIcHourglassEmpty48Px,
  materialIconIcHourglassFull24Px,
  materialIconIcHourglassFull48Px,
  materialIconIcHttp24Px,
  materialIconIcHttp48Px,
  materialIconIcHttps24Px,
  materialIconIcHttps48Px,
} from '@triangular/material-icons/icons';

@Component({
  selector: 'app-icons-h',
  templateUrl: './icons-h.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
})
export class IconsHComponent {
  icons = [
    materialIconIcHd24Px,
    materialIconIcHdrOff24Px,
    materialIconIcHdrOff48Px,
    materialIconIcHdrOn24Px,
    materialIconIcHdrOn48Px,
    materialIconIcHdrStrong24Px,
    materialIconIcHdrStrong48Px,
    materialIconIcHdrWeak24Px,
    materialIconIcHdrWeak48Px,
    materialIconIcHeadset24Px,
    materialIconIcHeadset48Px,
    materialIconIcHeadsetMic24Px,
    materialIconIcHeadsetMic48Px,
    materialIconIcHealing24Px,
    materialIconIcHealing48Px,
    materialIconIcHearing24Px,
    materialIconIcHearing48Px,
    materialIconIcHelp24Px,
    materialIconIcHelp48Px,
    materialIconIcHelpOutline24Px,
    materialIconIcHighQuality24Px,
    materialIconIcHighQuality48Px,
    materialIconIcHighlight24Px,
    materialIconIcHighlight48Px,
    materialIconIcHighlightOff24Px,
    materialIconIcHighlightOff48Px,
    materialIconIcHistory24Px,
    materialIconIcHistory48Px,
    materialIconIcHome24Px,
    materialIconIcHome48Px,
    materialIconIcHotTub24Px,
    materialIconIcHotTub48Px,
    materialIconIcHotel24Px,
    materialIconIcHotel48Px,
    materialIconIcHourglassEmpty24Px,
    materialIconIcHourglassEmpty48Px,
    materialIconIcHourglassFull24Px,
    materialIconIcHourglassFull48Px,
    materialIconIcHttp24Px,
    materialIconIcHttp48Px,
    materialIconIcHttps24Px,
    materialIconIcHttps48Px,
  ];

  constructor(private registry: MaterialIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
