import { Component, ViewEncapsulation } from '@angular/core';
import { MaterialIconsRegistry, } from '@triangular/material-icons';

import {
  materialIconIcGTranslate24Px,
  materialIconIcGTranslate48Px,
  materialIconIcGamepad24Px,
  materialIconIcGamepad48Px,
  materialIconIcGames24Px,
  materialIconIcGames48Px,
  materialIconIcGavel24Px,
  materialIconIcGavel48Px,
  materialIconIcGesture24Px,
  materialIconIcGesture48Px,
  materialIconIcGetApp24Px,
  materialIconIcGetApp48Px,
  materialIconIcGif24Px,
  materialIconIcGolfCourse24Px,
  materialIconIcGolfCourse48Px,
  materialIconIcGpsFixed24Px,
  materialIconIcGpsFixed48Px,
  materialIconIcGpsNotFixed24Px,
  materialIconIcGpsNotFixed48Px,
  materialIconIcGpsOff24Px,
  materialIconIcGpsOff48Px,
  materialIconIcGrade24Px,
  materialIconIcGrade48Px,
  materialIconIcGradient24Px,
  materialIconIcGradient48Px,
  materialIconIcGrain24Px,
  materialIconIcGrain48Px,
  materialIconIcGraphicEq24Px,
  materialIconIcGraphicEq48Px,
  materialIconIcGridOff24Px,
  materialIconIcGridOff48Px,
  materialIconIcGridOn24Px,
  materialIconIcGridOn48Px,
  materialIconIcGroup18Px,
  materialIconIcGroup24Px,
  materialIconIcGroup48Px,
  materialIconIcGroupAdd18Px,
  materialIconIcGroupAdd24Px,
  materialIconIcGroupAdd48Px,
  materialIconIcGroupWork24Px,
  materialIconIcGroupWork48Px,
} from '@triangular/material-icons/icons';

@Component({
  selector: 'app-icons-g',
  templateUrl: './icons-g.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
})
export class IconsGComponent {
  icons = [
    materialIconIcGTranslate24Px,
    materialIconIcGTranslate48Px,
    materialIconIcGamepad24Px,
    materialIconIcGamepad48Px,
    materialIconIcGames24Px,
    materialIconIcGames48Px,
    materialIconIcGavel24Px,
    materialIconIcGavel48Px,
    materialIconIcGesture24Px,
    materialIconIcGesture48Px,
    materialIconIcGetApp24Px,
    materialIconIcGetApp48Px,
    materialIconIcGif24Px,
    materialIconIcGolfCourse24Px,
    materialIconIcGolfCourse48Px,
    materialIconIcGpsFixed24Px,
    materialIconIcGpsFixed48Px,
    materialIconIcGpsNotFixed24Px,
    materialIconIcGpsNotFixed48Px,
    materialIconIcGpsOff24Px,
    materialIconIcGpsOff48Px,
    materialIconIcGrade24Px,
    materialIconIcGrade48Px,
    materialIconIcGradient24Px,
    materialIconIcGradient48Px,
    materialIconIcGrain24Px,
    materialIconIcGrain48Px,
    materialIconIcGraphicEq24Px,
    materialIconIcGraphicEq48Px,
    materialIconIcGridOff24Px,
    materialIconIcGridOff48Px,
    materialIconIcGridOn24Px,
    materialIconIcGridOn48Px,
    materialIconIcGroup18Px,
    materialIconIcGroup24Px,
    materialIconIcGroup48Px,
    materialIconIcGroupAdd18Px,
    materialIconIcGroupAdd24Px,
    materialIconIcGroupAdd48Px,
    materialIconIcGroupWork24Px,
    materialIconIcGroupWork48Px,
  ];

  constructor(private registry: MaterialIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
