import { Component, ViewEncapsulation } from '@angular/core';
import { MaterialIconsRegistry, } from '@triangular/material-icons';

import {
  materialIconIcNature24Px,
  materialIconIcNature48Px,
  materialIconIcNaturePeople24Px,
  materialIconIcNaturePeople48Px,
  materialIconIcNavigateBefore24Px,
  materialIconIcNavigateBefore48Px,
  materialIconIcNavigateNext24Px,
  materialIconIcNavigateNext48Px,
  materialIconIcNavigation24Px,
  materialIconIcNavigation48Px,
  materialIconIcNearMe24Px,
  materialIconIcNearMe48Px,
  materialIconIcNetworkCell18Px,
  materialIconIcNetworkCell24Px,
  materialIconIcNetworkCell48Px,
  materialIconIcNetworkCheck24Px,
  materialIconIcNetworkCheck48Px,
  materialIconIcNetworkLocked24Px,
  materialIconIcNetworkLocked48Px,
  materialIconIcNetworkWifi18Px,
  materialIconIcNetworkWifi24Px,
  materialIconIcNetworkWifi48Px,
  materialIconIcNewReleases24Px,
  materialIconIcNewReleases48Px,
  materialIconIcNextWeek24Px,
  materialIconIcNextWeek48Px,
  materialIconIcNfc24Px,
  materialIconIcNfc48Px,
  materialIconIcNoEncryption24Px,
  materialIconIcNoEncryption48Px,
  materialIconIcNoSim24Px,
  materialIconIcNoSim48Px,
  materialIconIcNotInterested24Px,
  materialIconIcNotInterested48Px,
  materialIconIcNote24Px,
  materialIconIcNote48Px,
  materialIconIcNoteAdd24Px,
  materialIconIcNoteAdd48Px,
  materialIconIcNotifications24Px,
  materialIconIcNotifications48Px,
  materialIconIcNotificationsActive24Px,
  materialIconIcNotificationsActive48Px,
  materialIconIcNotificationsNone24Px,
  materialIconIcNotificationsNone48Px,
  materialIconIcNotificationsOff24Px,
  materialIconIcNotificationsOff48Px,
  materialIconIcNotificationsPaused24Px,
  materialIconIcNotificationsPaused48Px,
} from '@triangular/material-icons/icons';

@Component({
  selector: 'app-icons-n',
  templateUrl: './icons-n.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
})
export class IconsNComponent {
  icons = [
    materialIconIcNature24Px,
    materialIconIcNature48Px,
    materialIconIcNaturePeople24Px,
    materialIconIcNaturePeople48Px,
    materialIconIcNavigateBefore24Px,
    materialIconIcNavigateBefore48Px,
    materialIconIcNavigateNext24Px,
    materialIconIcNavigateNext48Px,
    materialIconIcNavigation24Px,
    materialIconIcNavigation48Px,
    materialIconIcNearMe24Px,
    materialIconIcNearMe48Px,
    materialIconIcNetworkCell18Px,
    materialIconIcNetworkCell24Px,
    materialIconIcNetworkCell48Px,
    materialIconIcNetworkCheck24Px,
    materialIconIcNetworkCheck48Px,
    materialIconIcNetworkLocked24Px,
    materialIconIcNetworkLocked48Px,
    materialIconIcNetworkWifi18Px,
    materialIconIcNetworkWifi24Px,
    materialIconIcNetworkWifi48Px,
    materialIconIcNewReleases24Px,
    materialIconIcNewReleases48Px,
    materialIconIcNextWeek24Px,
    materialIconIcNextWeek48Px,
    materialIconIcNfc24Px,
    materialIconIcNfc48Px,
    materialIconIcNoEncryption24Px,
    materialIconIcNoEncryption48Px,
    materialIconIcNoSim24Px,
    materialIconIcNoSim48Px,
    materialIconIcNotInterested24Px,
    materialIconIcNotInterested48Px,
    materialIconIcNote24Px,
    materialIconIcNote48Px,
    materialIconIcNoteAdd24Px,
    materialIconIcNoteAdd48Px,
    materialIconIcNotifications24Px,
    materialIconIcNotifications48Px,
    materialIconIcNotificationsActive24Px,
    materialIconIcNotificationsActive48Px,
    materialIconIcNotificationsNone24Px,
    materialIconIcNotificationsNone48Px,
    materialIconIcNotificationsOff24Px,
    materialIconIcNotificationsOff48Px,
    materialIconIcNotificationsPaused24Px,
    materialIconIcNotificationsPaused48Px,
  ];

  constructor(private registry: MaterialIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
